import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "bn" | "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  bn: {
    // Navigation
    "nav.dashboard": "ড্যাশবোর্ড",
    "nav.transactions": "লেনদেন",
    "nav.add_transaction": "লেনদেন যোগ করুন",
    "nav.all_transactions": "সকল লেনদেন",
    "nav.recent_transactions": "সাম্প্রতিক লেনদেন",
    "nav.sales_orders": "বিক্রয় ও অর্ডার",
    "nav.new_order": "নতুন অর্ডার",
    "nav.order_history": "অর্ডারের ইতিহাস",
    "nav.customers": "গ্রাহকগণ",
    "nav.inventory": "মজুদ",
    "nav.add_product": "পণ্য যোগ করুন",
    "nav.add_company": "কোম্পানি যোগ করুন",
    "nav.stock_list": "স্টক তালিকা",
    "nav.categories": "বিভাগসমূহ",
    "nav.hr": "মানব সম্পদ",
    "nav.employees": "কর্মীগণ",
    "nav.payroll": "বেতন",
    "nav.attendance": "উপস্থিতি",
    "nav.accounting": "হিসাব",
    "nav.daily_ledger": "দৈনিক হিসাব",
    "nav.expense_report": "ব্যয় প্রতিবেদন",
    "nav.settings": "সেটিংস",
    "nav.system_config": "সিস্টেম কনফিগারেশন",
    "nav.user_roles": "ব্যবহারকারীর ভূমিকা",
    // Dashboard
    "dashboard.title": "ড্যাশবোর্ড",
    "dashboard.welcome": "স্বাগতম, আল-ইয়ামেন বিজনেস",
    "dashboard.total_revenue": "মোট আয়",
    "dashboard.total_expenses": "মোট ব্যয়",
    "dashboard.net_profit": "নেট মুনাফা",
    "dashboard.total_orders": "মোট অর্ডার",
    "dashboard.recent_activity": "সাম্প্রতিক কার্যক্রম",
    "dashboard.monthly_overview": "মাসিক সারসংক্ষেপ",
    "dashboard.top_products": "শীর্ষ পণ্য",
    "dashboard.quick_stats": "দ্রুত পরিসংখ্যান",
    // Common
    "common.add": "যোগ করুন",
    "common.edit": "সম্পাদনা",
    "common.delete": "মুছুন",
    "common.save": "সংরক্ষণ",
    "common.cancel": "বাতিল",
    "common.search": "খুঁজুন",
    "common.filter": "ফিল্টার",
    "common.export": "রপ্তানি",
    "common.print": "প্রিন্ট",
    "common.loading": "লোড হচ্ছে...",
    "common.no_data": "কোনো ডেটা নেই",
    "common.amount": "পরিমাণ",
    "common.date": "তারিখ",
    "common.status": "অবস্থা",
    "common.action": "কার্যক্রম",
    "common.name": "নাম",
    "common.description": "বিবরণ",
    "common.type": "ধরন",
    "common.category": "বিভাগ",
    "common.total": "মোট",
    "common.active": "সক্রিয়",
    "common.inactive": "নিষ্ক্রিয়",
    "common.pending": "অপেক্ষমান",
    "common.completed": "সম্পন্ন",
    "common.cancelled": "বাতিল",
    "common.view_all": "সব দেখুন",
    "common.phone": "ফোন",
    "common.email": "ইমেইল",
    "common.address": "ঠিকানা",
    "common.salary": "বেতন",
    "common.department": "বিভাগ",
    "common.position": "পদ",
    "common.quantity": "পরিমাণ",
    "common.price": "মূল্য",
    "common.stock": "স্টক",
    "common.revenue": "আয়",
    "common.profit": "মুনাফা",
    "common.loss": "ক্ষতি",
    "common.income": "আয়",
    "common.expense": "ব্যয়",
    "common.balance": "ব্যালেন্স",
    "common.invoice": "ইনভয়েস",
    "common.payment": "পেমেন্ট",
    "common.customer": "গ্রাহক",
    "common.supplier": "সরবরাহকারী",
    "common.product": "পণ্য",
    "common.order": "অর্ডার",
    "common.language": "ভাষা",
    "common.settings": "সেটিংস",
    // Stats
    "stats.this_month": "এই মাসে",
    "stats.last_month": "গত মাসে",
    "stats.growth": "বৃদ্ধি",
    "stats.change": "পরিবর্তন",
    // Transactions
    "transactions.title": "লেনদেন",
    "transactions.add_new": "নতুন লেনদেন যোগ করুন",
    "transactions.income": "আয়",
    "transactions.expense": "ব্যয়",
    "transactions.transfer": "স্থানান্তর",
    "transactions.reference": "রেফারেন্স",
    "transactions.notes": "নোট",
    // Inventory
    "inventory.title": "মজুদ",
    "inventory.add_product": "পণ্য যোগ করুন",
    "inventory.product_name": "পণ্যের নাম",
    "inventory.sku": "SKU",
    "inventory.unit": "একক",
    "inventory.min_stock": "সর্বনিম্ন স্টক",
    "inventory.current_stock": "বর্তমান স্টক",
    "inventory.low_stock": "কম স্টক",
    "inventory.out_of_stock": "স্টক শেষ",
    // HR
    "hr.title": "মানব সম্পদ",
    "hr.add_employee": "কর্মী যোগ করুন",
    "hr.employee_id": "কর্মী আইডি",
    "hr.join_date": "যোগদানের তারিখ",
    "hr.present": "উপস্থিত",
    "hr.absent": "অনুপস্থিত",
    "hr.leave": "ছুটি",
    // Settings
    "settings.title": "সেটিংস",
    "settings.company_name": "কোম্পানির নাম",
    "settings.business_type": "ব্যবসার ধরন",
    "settings.currency": "মুদ্রা",
    "settings.timezone": "সময় অঞ্চল",
    "settings.language_settings": "ভাষা সেটিংস",
    "settings.user_management": "ব্যবহারকারী ব্যবস্থাপনা",
    "settings.role": "ভূমিকা",
    "settings.permissions": "অনুমতি",
    // Company
    "company.al_yamen": "আল-ইয়ামেন",
    "company.tagline": "ব্যবসায়িক ব্যবস্থাপনা সিস্টেম",
  },
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.transactions": "Transactions",
    "nav.add_transaction": "Add Transaction",
    "nav.all_transactions": "All Transactions",
    "nav.recent_transactions": "Recent Transactions",
    "nav.sales_orders": "Sales & Orders",
    "nav.new_order": "New Order",
    "nav.order_history": "Order History",
    "nav.customers": "Customers",
    "nav.inventory": "Inventory",
    "nav.add_product": "Add Product",
    "nav.add_company": "Add Company",
    "nav.stock_list": "Stock List",
    "nav.categories": "Categories",
    "nav.hr": "Human Resources",
    "nav.employees": "Employees",
    "nav.payroll": "Payroll",
    "nav.attendance": "Attendance",
    "nav.accounting": "Accounting",
    "nav.daily_ledger": "Daily Ledger",
    "nav.expense_report": "Expense Report",
    "nav.settings": "Settings",
    "nav.system_config": "System Config",
    "nav.user_roles": "User Roles",
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome, Al-Yamen Business",
    "dashboard.total_revenue": "Total Revenue",
    "dashboard.total_expenses": "Total Expenses",
    "dashboard.net_profit": "Net Profit",
    "dashboard.total_orders": "Total Orders",
    "dashboard.recent_activity": "Recent Activity",
    "dashboard.monthly_overview": "Monthly Overview",
    "dashboard.top_products": "Top Products",
    "dashboard.quick_stats": "Quick Stats",
    // Common
    "common.add": "Add",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.print": "Print",
    "common.loading": "Loading...",
    "common.no_data": "No data available",
    "common.amount": "Amount",
    "common.date": "Date",
    "common.status": "Status",
    "common.action": "Action",
    "common.name": "Name",
    "common.description": "Description",
    "common.type": "Type",
    "common.category": "Category",
    "common.total": "Total",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.pending": "Pending",
    "common.completed": "Completed",
    "common.cancelled": "Cancelled",
    "common.view_all": "View All",
    "common.phone": "Phone",
    "common.email": "Email",
    "common.address": "Address",
    "common.salary": "Salary",
    "common.department": "Department",
    "common.position": "Position",
    "common.quantity": "Quantity",
    "common.price": "Price",
    "common.stock": "Stock",
    "common.revenue": "Revenue",
    "common.profit": "Profit",
    "common.loss": "Loss",
    "common.income": "Income",
    "common.expense": "Expense",
    "common.balance": "Balance",
    "common.invoice": "Invoice",
    "common.payment": "Payment",
    "common.customer": "Customer",
    "common.supplier": "Supplier",
    "common.product": "Product",
    "common.order": "Order",
    "common.language": "Language",
    "common.settings": "Settings",
    // Stats
    "stats.this_month": "This Month",
    "stats.last_month": "Last Month",
    "stats.growth": "Growth",
    "stats.change": "Change",
    // Transactions
    "transactions.title": "Transactions",
    "transactions.add_new": "Add New Transaction",
    "transactions.income": "Income",
    "transactions.expense": "Expense",
    "transactions.transfer": "Transfer",
    "transactions.reference": "Reference",
    "transactions.notes": "Notes",
    // Inventory
    "inventory.title": "Inventory",
    "inventory.add_product": "Add Product",
    "inventory.product_name": "Product Name",
    "inventory.sku": "SKU",
    "inventory.unit": "Unit",
    "inventory.min_stock": "Min Stock",
    "inventory.current_stock": "Current Stock",
    "inventory.low_stock": "Low Stock",
    "inventory.out_of_stock": "Out of Stock",
    // HR
    "hr.title": "Human Resources",
    "hr.add_employee": "Add Employee",
    "hr.employee_id": "Employee ID",
    "hr.join_date": "Join Date",
    "hr.present": "Present",
    "hr.absent": "Absent",
    "hr.leave": "Leave",
    // Settings
    "settings.title": "Settings",
    "settings.company_name": "Company Name",
    "settings.business_type": "Business Type",
    "settings.currency": "Currency",
    "settings.timezone": "Timezone",
    "settings.language_settings": "Language Settings",
    "settings.user_management": "User Management",
    "settings.role": "Role",
    "settings.permissions": "Permissions",
    // Company
    "company.al_yamen": "Al-Yamen",
    "company.tagline": "Business Management System",
  },
  ar: {
    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.transactions": "المعاملات",
    "nav.add_transaction": "إضافة معاملة",
    "nav.all_transactions": "جميع المعاملات",
    "nav.recent_transactions": "المعاملات الأخيرة",
    "nav.sales_orders": "المبيعات والطلبات",
    "nav.new_order": "طلب جديد",
    "nav.order_history": "تاريخ الطلبات",
    "nav.customers": "العملاء",
    "nav.inventory": "المخزون",
    "nav.add_product": "إضافة منتج",
    "nav.add_company": "إضافة شركة",
    "nav.stock_list": "قائمة المخزون",
    "nav.categories": "الفئات",
    "nav.hr": "الموارد البشرية",
    "nav.employees": "الموظفون",
    "nav.payroll": "كشف الرواتب",
    "nav.attendance": "الحضور",
    "nav.accounting": "المحاسبة",
    "nav.daily_ledger": "دفتر اليومية",
    "nav.expense_report": "تقرير المصروفات",
    "nav.settings": "الإعدادات",
    "nav.system_config": "إعدادات النظام",
    "nav.user_roles": "أدوار المستخدمين",
    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.welcome": "مرحباً، اليمن للأعمال",
    "dashboard.total_revenue": "إجمالي الإيرادات",
    "dashboard.total_expenses": "إجمالي المصروفات",
    "dashboard.net_profit": "صافي الربح",
    "dashboard.total_orders": "إجمالي الطلبات",
    "dashboard.recent_activity": "النشاط الأخير",
    "dashboard.monthly_overview": "نظرة عامة شهرية",
    "dashboard.top_products": "أفضل المنتجات",
    "dashboard.quick_stats": "إحصائيات سريعة",
    // Common
    "common.add": "إضافة",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.export": "تصدير",
    "common.print": "طباعة",
    "common.loading": "جارٍ التحميل...",
    "common.no_data": "لا توجد بيانات",
    "common.amount": "المبلغ",
    "common.date": "التاريخ",
    "common.status": "الحالة",
    "common.action": "الإجراء",
    "common.name": "الاسم",
    "common.description": "الوصف",
    "common.type": "النوع",
    "common.category": "الفئة",
    "common.total": "الإجمالي",
    "common.active": "نشط",
    "common.inactive": "غير نشط",
    "common.pending": "معلق",
    "common.completed": "مكتمل",
    "common.cancelled": "ملغي",
    "common.view_all": "عرض الكل",
    "common.phone": "الهاتف",
    "common.email": "البريد الإلكتروني",
    "common.address": "العنوان",
    "common.salary": "الراتب",
    "common.department": "القسم",
    "common.position": "المنصب",
    "common.quantity": "الكمية",
    "common.price": "السعر",
    "common.stock": "المخزون",
    "common.revenue": "الإيرادات",
    "common.profit": "الربح",
    "common.loss": "الخسارة",
    "common.income": "الدخل",
    "common.expense": "المصروف",
    "common.balance": "الرصيد",
    "common.invoice": "الفاتورة",
    "common.payment": "الدفع",
    "common.customer": "العميل",
    "common.supplier": "المورد",
    "common.product": "المنتج",
    "common.order": "الطلب",
    "common.language": "اللغة",
    "common.settings": "الإعدادات",
    // Stats
    "stats.this_month": "هذا الشهر",
    "stats.last_month": "الشهر الماضي",
    "stats.growth": "النمو",
    "stats.change": "التغيير",
    // Transactions
    "transactions.title": "المعاملات",
    "transactions.add_new": "إضافة معاملة جديدة",
    "transactions.income": "دخل",
    "transactions.expense": "مصروف",
    "transactions.transfer": "تحويل",
    "transactions.reference": "المرجع",
    "transactions.notes": "ملاحظات",
    // Inventory
    "inventory.title": "المخزون",
    "inventory.add_product": "إضافة منتج",
    "inventory.product_name": "اسم المنتج",
    "inventory.sku": "رمز المنتج",
    "inventory.unit": "الوحدة",
    "inventory.min_stock": "الحد الأدنى للمخزون",
    "inventory.current_stock": "المخزون الحالي",
    "inventory.low_stock": "مخزون منخفض",
    "inventory.out_of_stock": "نفد من المخزون",
    // HR
    "hr.title": "الموارد البشرية",
    "hr.add_employee": "إضافة موظف",
    "hr.employee_id": "رقم الموظف",
    "hr.join_date": "تاريخ الالتحاق",
    "hr.present": "حاضر",
    "hr.absent": "غائب",
    "hr.leave": "إجازة",
    // Settings
    "settings.title": "الإعدادات",
    "settings.company_name": "اسم الشركة",
    "settings.business_type": "نوع العمل",
    "settings.currency": "العملة",
    "settings.timezone": "المنطقة الزمنية",
    "settings.language_settings": "إعدادات اللغة",
    "settings.user_management": "إدارة المستخدمين",
    "settings.role": "الدور",
    "settings.permissions": "الصلاحيات",
    // Company
    "company.al_yamen": "اليمن",
    "company.tagline": "نظام إدارة الأعمال",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("al-yamen-language");
    return (saved as Language) || "bn";
  });

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    localStorage.setItem("al-yamen-language", language);
    document.documentElement.setAttribute("lang", language);
    document.documentElement.setAttribute("dir", dir);
  }, [language, dir]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
